IMAGE_CURRENT_VERSION=23.11.01
IMAGE_DEFAULT_REPOSITORY=samples/appdemotest
#IMAGE_DEFAULT_REPOSITORY=samples/aspnetcoredemoapp
CHART=asp-net-core-web-app-demo

IMAGE_REPOSITORY="${IMAGE_REPOSITORY:-$IMAGE_DEFAULT_REPOSITORY}"
IMAGE_TAG="${IMAGE_TAG:-$IMAGE_CURRENT_VERSION}"
INSTANCE="${INSTANCE:-app-demo}"
ROUTE_HOSTNAME="${ROUTE_HOSTNAME:-$INSTANCE}"
HELMWAIT="${HELMWAIT:-120s}"
CHECKIMAGE="${CHECKIMAGE:-1}"
