---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: azure-devops-ci-cd
    app.kubernetes.io/name: azure-devops-ci-cd
    app.kubernetes.io/part-of: azure-devops
  name: ci-cd
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
    - configmaps
    - pods
    - secrets
    - services
    - services/proxy
    - endpoints
    - persistentvolumeclaims
  verbs:
    - "*"
- apiGroups: [""] # "" indicates the core API group
  resources:
    - pods/log
    - events
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
    - deployments/rollback
    - deployments/scale
    - deployments/status
    - replicasets  # needed for 'helm upgrade --wait'
    - replicasets/scale
    - replicasets/status
    - statefulsets
    - statefulsets/scale
    - statefulsets/status
    - daemonsets
    - daemonsets/status
  verbs:
    - "*"
- apiGroups:
    - batch
  resources:
    - cronjobs
    - jobs
  verbs:
    - "*"
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - "*"
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
    - ingresses
  verbs:
    - "*"
- apiGroups:
    - route.openshift.io/v1
  resources:
    - route
  verbs:
    - "*"
- apiGroups:
    - monitoring.coreos.com
  resources:
    - prometheusrules
    - podmonitors
    - servicemonitors
  verbs:
    - "*"
