---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: azure-devops-ci-cd
    app.kubernetes.io/name: azure-devops-ci-cd
    app.kubernetes.io/part-of: azure-devops
  name: ci-cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: azure-devops-ci-cd
    app.kubernetes.io/name: azure-devops-ci-cd
    app.kubernetes.io/part-of: azure-devops
  name: ci-cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ci-cd
subjects:
  - kind: ServiceAccount
    name: ci-cd
